handle_args: char:1; exception: TestException().
----------------
Coverage Report:

__main__: exc-TF-TXR_{}.py:
   4   def top(arg):
   5     try:
   6       try:
   7         try2(arg)
   8 !     except:
   9 !       exc()
  10 %     if arg == 1:
  11         raise TestException
 ...
  15
  16   def try2(arg):
  17     if arg == 0: return 0
  18     if arg == 1: return 1
  19 !   raise E2
  20

__main__: exc-TF-TXR_{}.py: 15 traceable; 11 covered; 0 ignored; 0 ignored but covered; 4 not covered.
