handle_args: char:1; exception: TestException().
----------------
Coverage Report:

__main__: exc-TF-TXR_{}.py: 15 traceable; 15 covered; 0 ignored; 0 ignored but covered; 0 not covered.
